### ISSUE TITLE
[Bug] az extension add gives 'ERROR: An error occurred. Pip failed with status code 1. Use --debug for more information.'

### ISSUE THREAD

**Issue by BramCoding** [Azure/azure-devops-cli-extension#1115]
**Describe the bug**
Since March 31 I am failing to install an az extension using my DevOps pipeline. I am managing a Digital Twin Instance so I need to 'azure-iot' extension to be installed on my hosted agent vs2017-win2016. Until March 31 everything went fine and the extension got installed correctly so I could use it in following scripts. 
When I try to install the extension using: 'az extension add --name azure-iot --debug' I get the following error: 'ERROR: An error occurred. Pip failed with status code 1. Use --debug for more information.'

**To Reproduce**
Azure Cli Version: 2.21.2
Use az --version 
Look for something like-

Azure-Devops extension version: 0.18.0
Use az --version
Look for something like-

1. create cmd script in DevOps Release pipeline
2. add command 'az extension add --name azure-iot --debug' to the cmd script
3. Run DevOps release pipeline with Hosted Agent vs2017-win2016

**Expected behavior**
I expected the 'azure-iot' extension to install for the pipeline run.

**Debug logs**

`

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 509, in get_current_account_user
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 74, in _wrapped_func
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 57, in _decorator
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 530, in _get_user_azure_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 511, in get_current_account_user
knack.util.CLIError: There are no active accounts.

INFO: cli.azure.cli.core.decorators: Suppress exception:
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 60, in <module>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/__main__.py", line 53, in <module>
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/decorators.py", line 74, in _wrapped_func
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/telemetry.py", line 540, in _get_azure_subscription_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 535, in get_subscription_id
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 518, in get_subscription
knack.util.CLIError: Please run 'az login' to setup account.

INFO: telemetry.save: Save telemetry record of length 2914 in cache
INFO: telemetry.check: Positive: The C:\Users\VssAdministrator\.azure\telemetry.txt does not exist.
INFO: telemetry.main: Begin creating telemetry upload process.
INFO: telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\telemetry\__init__.pyc C:\Users\VssAdministrator\.azure"
INFO: telemetry.process: Return from creating process
INFO: telemetry.main: Finish creating telemetry upload process.
##[error]Cmd.exe exited with code '1'.
`

**Additional context**
As explained this started happening on March 31. Worked fine before.

**Comment by fgheysels** [comment]
We're running into a similar issue when using the azure-iot extension from within an Azure Devops pipeline.
When running the command
```pwsh
az extension add --name azure-iot --debug
```
We get a similar log as the one that is mentionned above.  One thing that draws my attention is this output:

```
2021-04-07T11:24:48.4557103Z   Downloading paho-mqtt-1.5.0.tar.gz (99 kB)
2021-04-07T11:24:48.4558285Z   Added paho-mqtt==1.5.0 from https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz#sha256=e3d286198baaea195c8b3bc221941d25a3ab0e1507fc1779bdb7473806394be4 (from azure-iot==0.10.10) to build tracker 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\pip-req-tracker-pxyt_p8d'
2021-04-07T11:24:48.4559677Z     Running setup.py (path:C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-2r0anm9h\paho-mqtt_614c37e4df7840adb34803b6b20cc5d5\setup.py) egg_info for package paho-mqtt
2021-04-07T11:24:48.4560631Z     Created temporary directory: C:\Users\VSSADM~1\AppData\Local\Temp\pip-pip-egg-info-rbjp8dg4
2021-04-07T11:24:48.4561499Z     Running command python setup.py egg_info
2021-04-07T11:24:48.4562280Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'include_package_data'
2021-04-07T11:24:48.4563170Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
2021-04-07T11:24:48.4564903Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
2021-04-07T11:24:48.4566467Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
2021-04-07T11:24:48.4567342Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
2021-04-07T11:24:48.4568309Z     C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
2021-04-07T11:24:48.4569023Z     usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
2021-04-07T11:24:48.4569537Z        or: setup.py --help [cmd1 cmd2 ...]
2021-04-07T11:24:48.4569952Z        or: setup.py --help-commands
2021-04-07T11:24:48.4570348Z        or: setup.py cmd --help
2021-04-07T11:24:48.4570519Z 
2021-04-07T11:24:48.4570873Z     error: invalid command 'egg_info'
2021-04-07T11:24:48.4572124Z WARNING: Discarding https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz#sha256=e3d286198baaea195c8b3bc221941d25a3ab0e1507fc1779bdb7473806394be4 (from https://pypi.org/simple/paho-mqtt/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2021-04-07T11:24:48.4573284Z ERROR: Could not find a version that satisfies the requirement paho-mqtt==1.5.0 (from azure-iot)
2021-04-07T11:24:48.4573866Z ERROR: No matching distribution found for paho-mqtt==1.5.0
2021-04-07T11:24:48.4574307Z Exception information:
2021-04-07T11:24:48.4574705Z Traceback (most recent call last):
2021-04-07T11:24:48.4575343Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
2021-04-07T11:24:48.4576481Z     requirements, max_rounds=try_to_avoid_resolution_too_deep,
2021-04-07T11:24:48.4577932Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
2021-04-07T11:24:48.4578581Z     state = resolution.resolve(requirements, max_rounds=max_rounds)
2021-04-07T11:24:48.4579236Z   File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 357, in resolve
2021-04-07T11:24:48.4579820Z     raise ResolutionImpossible(causes)
2021-04-07T11:24:48.4582444Z pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('paho-mqtt==1.5.0'), parent=LinkCandidate('file:///C:/Users/VSSADM%7E1/AppData/Local/Temp/tmpxti_34oo/azure_iot-0.10.10-py3-none-any.whl'))]
````

**Comment by fgheysels** [comment]
I have changed my pipeline so that I'm using a Linux hosted agent (ubuntu-18.04) instead of Windows-2019.  The problem does not occur when running on a LInux hosted agent.

**Comment by miketimofeev** [comment]
@fgheysels @BramCoding I'm from the team owning hosted VMs administration and deployment. We're investigating the issue in our repo here as well actions/virtual-environments#3143
Azure Cli has its own Python distribution, but the latest az-cli version seems to have a lack of setuptools and wheel python modules. The workaround is to install these modules in runtime via powershell:

```
$azPython = "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe"
& $azpython -m pip install setuptools
& $azpython -m pip install install wheel
```

**Comment by roopsduhra** [comment]
Thanks @miketimofeev, 

The above workaround has worked.

This issue only start occurring about week ago. I was able to run the command **az extension add --name azure-iot** via the pipeline. Can you please advise when the permanent fix would be applied on **hosted agent (windows image)** so when can update our code.

**Comment by miketimofeev** [comment]
@roopsduhra I'm afraid it should be fixed from the azure-cli side because we install the latest version automatically during the VM image build. Related issue: https://github.com/Azure/azure-cli/issues/17555

**Comment by jiasli** [comment]
Please see https://github.com/Azure/azure-cli/issues/18703#issuecomment-873843943
