### ISSUE TITLE
 'GetDefinitionsResponseValue' has no len() on pipelines update

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/azure-devops-cli-extension#1136]
## Describe the bug

**Command Name**
`az pipelines update
Extension Name: azure-devops. Version: 0.18.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
object of type 'GetDefinitionsResponseValue' has no len()
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/home/svi_core_2/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/svi_core_2/.azure/cliextensions/azure-devops/azext_devops/dev/pipelines/pipeline_create.py", line 186, in pipeline_update
    id = get_definition_id_from_name(name, pipeline_client, project)
  File "/home/svi_core_2/.azure/cliextensions/azure-devops/azext_devops/dev/pipelines/build_definition.py", line 106, in get_definition_id_from_name
    if len(definition_references) == 1:
TypeError: object of type 'GetDefinitionsResponseValue' has no len()

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az pipelines update --name {} --organization {} --project {} --branch {} --yml-path {} --debug`

## Expected Behavior
Looking at the code, there is a reason why this isnt working: 
https://github.com/Azure/azure-devops-cli-extension/blob/effbefe7bc6a41d3f319790f287de49558bd5fa6/azure-devops/azext_devops/devops_sdk/released/build/build_client.py#L576-L589 

This object doesnt have a len.
https://github.com/Azure/azure-devops-cli-extension/blob/effbefe7bc6a41d3f319790f287de49558bd5fa6/azure-devops/azext_devops/dev/pipelines/build_definition.py#L103-L108

Even then, the `GetDefinitionsResponseValue` doesnt have `project` or `id` fields.

## Environment Summary
```
Linux-5.3.0-26-generic-x86_64-with-debian-10.6
Python 3.6.10
Installer: DEB

azure-cli 2.24.2

Extensions:
azure-devops 0.18.0

```

**Comment by gauravsaralMs** [comment]
@POLIMATISUNILBABU : can you look into this?

**Comment by roshan-sy** [comment]
Observation
![image](https://user-images.githubusercontent.com/83656375/133569325-65d419f8-3df8-47e8-a5c8-44ea0396fd75.png)

looks like **name**  parameter is got removed from the API itself. (Need to verify)

RCA:
Unable to fetch pipeline id from name

Mitigation strategy:
1. Remove **name** property from command
2. or keep **name** and Throw error if command executed with **name**


```
Time taken for Proposal : 2 days
Code implementation and testing : 1 day
```

**Comment by gauravsaralMs** [comment]
> Observation
> ![image](https://user-images.githubusercontent.com/83656375/133569325-65d419f8-3df8-47e8-a5c8-44ea0396fd75.png)
> 
> looks like **name** parameter is got removed from the API itself. (Need to verify)
> 
> RCA:
> Unable to fetch pipeline id from name
> 
> Mitigation strategy:
> 
> 1. Remove **name** property from command
> 2. or keep **name** and Throw error if command executed with **name**
> 
> ```
> Time taken for Proposal : 2 days
> Code implementation and testing : 1 day
> ```

for Mitigation strategy can we instead get id of the pipeline using name?

we need to make sure the scenario customer is trying to achieve is met post the fix

**Comment by roshan-sy** [comment]
> @roshan-sy for Mitigation strategy can we instead get id of the pipeline using name?
> 
> we need to make sure the scenario customer is trying to achieve is met post the fix

Noted

**Comment by gauravsaralMs** [comment]
given that `--name` is marked as deprecated we can remove it, just make sure that things are working with `-id`

https://github.com/Azure/azure-devops-cli-extension/blob/fab8405a174fc264d516c27ed66653efbac02a29/azure-devops/azext_devops/dev/pipelines/arguments.py#L88
