### ISSUE TITLE
Unable to use azure-devops extension commands

### ISSUE THREAD

**Issue by shehlmaltego** [Azure/azure-devops-cli-extension#1163]
## Describe the bug

**Command Name**
`az boards area project list
Extension Name: azure-devops. Version: 0.18.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
module 'keyring' has no attribute 'core'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 712, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/boards/area.py", line 24, in get_project_areas
    organization, project = resolve_instance_and_project(detect=detect,
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 362, in resolve_instance_and_project
    organization, project, _ = resolve_instance_project_and_repo(
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 331, in resolve_instance_project_and_repo
    git_info = get_vsts_info_from_current_remote_url()
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 395, in get_vsts_info_from_current_remote_url
    info = VstsGitUrlInfo(get_remote_url(VstsGitUrlInfo.is_vsts_url_candidate))
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/vsts_git_url_info.py", line 42, in __init__
    vsts_info = self.get_vsts_info(remote_url)
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/vsts_git_url_info.py", line 93, in get_vsts_info
    credentials = _get_credentials(uri)
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/services.py", line 56, in _get_credentials
    if PAT_ENV_VARIABLE_NAME in os.environ or get_credential(organization) is not None:
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/_credentials.py", line 17, in get_credential
    token = _get_credential(organization)
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/_credentials.py", line 26, in _get_credential
    cred_store = CredentialStore()
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/credential_store.py", line 19, in __init__
    self._initialize_keyring()
  File "/Users/spencerhehl/.azure/cliextensions/azure-devops/azext_devops/dev/common/credential_store.py", line 154, in _initialize_keyring
    keyring.core.init_backend(_only_builtin)
AttributeError: module 'keyring' has no attribute 'core'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az boards area project list`

## Environment Summary
```
macOS-11.4-arm64-arm-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.1

Extensions:
azure-devops 0.18.0

```

**Comment by SpencerHehl** [comment]
Solved by this answer in another thread: https://github.com/Azure/azure-devops-cli-extension/issues/1100#issuecomment-790207149

It is a very unhelpful error to throw here.

**Comment by shehlmaltego** [comment]
Solved by: https://github.com/Azure/azure-devops-cli-extension/issues/1100#issuecomment-790207149
