### ISSUE TITLE
issue with download image 2022.815.1

### ISSUE THREAD

**Issue by lmoiseichuk** [Azure/azure-devops-cli-extension#1292]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.25.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
File is not a zip file
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 718, in _run_job
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\six.py", line 703, in reraise
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 98, in download_package
    return artifact_tool.download_universal(organization, project, feed, name, version, path, file_filter)
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 42, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 57, in run_artifacttool
    artifacttool_dir = self._artifacttool_updater.get_latest_artifacttool(organization)
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 43, in get_latest_artifacttool
    artifacttool_binary_path = self._get_artifacttool(organization)
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 74, in _get_artifacttool
    _update_artifacttool(release_uri, release_id)
  File "C:\Users\lmoiseichuk\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool_updater.py", line 114, in _update_artifacttool
    f = zipfile.ZipFile(content)
  File "zipfile.py", line 1267, in __init__
  File "zipfile.py", line 1334, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Windows-10-10.0.22000-SP0
Python 3.10.5
Installer: MSI

azure-cli 2.39.0

Extensions:
azure-devops 0.25.0

Dependencies:
msal 1.18.0b1
azure-mgmt-resource 21.1.0b1
```

**Comment by lmoiseichuk** [comment]
parameters are internal information; I can share them for MS engineers

**Comment by lmoiseichuk** [comment]
To pass this problem temporarily has to disable auto-upgrade
`az config set auto-upgrade.enable=no`
