### ISSUE TITLE
[Bug] Unable to publish any artifacts - SSL connection could not be established

### ISSUE THREAD

**Issue by mbrancato** [Azure/azure-devops-cli-extension#459]
**Describe the bug**
Every time I attempt to publish an artifact, it fails

**To Reproduce**
Azure Cli Version: 
`azure-cli                         2.0.58`

Azure-Devops extension version: 
`azure-devops                       0.2.0`

1. login using `az login`
2. publish using `az artifacts universal publish`

**Expected behavior**
Package would publish with no error.

**Additional context**
Command output below:

```
# az artifacts universal publish --org "https://<name>.visualstudio.com/" --feed "test" --name "test" --version "1.0.0" --path .
Universal Packages is currently in preview.
[GetBuildDropManagerAsync] Try 1/5, non-retryable exception caught. Throwing. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
Encountered an unexpected error.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetInstanceIdAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at ArtifactTool.BuildDropManagerProvider.GetBuildDropManagerAsync(String serviceUrl, String patVar, ILogger commandBaseLogger, IAppTraceSource tracer, CancellationToken cancellationToken) in D:\a\1\s\src\ArtifactTool\Providers\BuildDropManager\BuildDropManagerProvider.cs:line 42
   at ArtifactTool.Commands.UPackPublishCommand.ExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\UPack\UPackPublishCommand.cs:line 49
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 113
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
```

**Comment by mbrancato** [comment]
Using debug, it fails when calling `artifacttool`.

**Comment by mitchdenny** [comment]
Thanks for reporting issue. Could we get a bit more information about your environment. What distribution of Linux are you running? Also - as a diagnostic could you try setting the org URL to https://dev.azure.com/<name>? It should work either way but just want to rule out something going on there.

Finally - do you have any proxies at play in your environment?

**Comment by mbrancato** [comment]
I'm using an Ubuntu release, its probably more like a dev stream. Do you mind to help me understand how to specify the organization and project like `https://company.visualstudio.com/Project Name/`? I did notice that the link seems to also be `https://dev.azure.org/company/`. Do you have certificate pinning enabled? I confirmed that the certificates are not the same, so that might make sense.

No proxies involved, but we do have some UTM that does inspection. I can avoid it pretty easily though.

I tried it in the following forms and just receive 404 errors:

```
# az artifacts universal publish --org "https://dev.azure.com/company/Project%20Name/" --feed "test" --name "test" --version "1.0.0" --path ./test
Universal Packages is currently in preview.
Failed to update Universal Packages tooling.
 Page not found.  Operation returned an invalid status code of 404.
```

```
# az artifacts universal publish --org "https://dev.azure.com/company/Project Name/" --feed "test" --name "test" --version "1.0.0" --path ./test
Universal Packages is currently in preview.
Failed to update Universal Packages tooling.
 Page not found.  Operation returned an invalid status code of 404.
```

**Comment by mitchdenny** [comment]
Set the org to https://dev.azure.com/org 

No need for the project in the URL.

**Comment by mbrancato** [comment]
I think I'm getting the same result.

```
# az artifacts universal publish --org "https://dev.azure.com/company" --feed "test" --name "test" --version "1.0.0" --path ./test
Universal Packages is currently in preview.
[GetBuildDropManagerAsync] Try 1/5, non-retryable exception caught. Throwing. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
Encountered an unexpected error.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception. ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:MODULE_RUN:unknown module name
   at Interop.SslInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor()
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor()
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.EnsureConnectedAsync(ConnectOptions optionsNeeded, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetInstanceIdAsync(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.LocationService.GetLocationDataAsync(Guid locationAreaIdentifier, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientInstanceAsync(Type managedType, Guid serviceIdentifier, CancellationToken cancellationToken, VssHttpRequestSettings settings, DelegatingHandler[] handlers)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientServiceImplAsync(Type requestedType, Guid serviceIdentifier, Func`4 getInstanceAsync, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssConnection.GetClientAsync[T](CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Content.Common.AsyncHttpRetryHelper`1.InvokeAsync(CancellationToken cancellationToken)
   at ArtifactTool.BuildDropManagerProvider.GetBuildDropManagerAsync(String serviceUrl, String patVar, ILogger commandBaseLogger, IAppTraceSource tracer, CancellationToken cancellationToken) in D:\a\1\s\src\ArtifactTool\Providers\BuildDropManager\BuildDropManagerProvider.cs:line 42
   at ArtifactTool.Commands.UPackPublishCommand.ExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\UPack\UPackPublishCommand.cs:line 49
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in D:\a\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 113
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
```

**Comment by zarenner** [comment]
Can you please confirm you have libssl1.0.0 installed? (https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#ubuntu)

**Comment by mbrancato** [comment]
I think I have what is needed based on the linker cache.

```
# ldconfig -p | grep libssl
	libssl3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl3.so
	libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
	libssl.so.1.0.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
	libssl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so
```

The default linking is to libssl1.1

```
# ls -la /usr/lib/x86_64-linux-gnu/libssl.so
lrwxrwxrwx 1 root root 13 Nov 22 12:40 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
```

**Comment by mbrancato** [comment]
For good measure I tried the container `microsoft/azure-cli` and the Azure CLI on Windows 10. Both seem unable to find (container) or extract (Windows) the artifact tool. They do both actively download artifacttool.

Container:
```
# docker run -v /path/to/test:/test -it microsoft/azure-cli
bash-4.4# az login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code E5763TTBN to authenticate.
[
  {

...

  }
]
bash-4.4# az extension add --name azure-devops
The installed extension 'azure-devops' is in preview.
bash-4.4# az artifacts universal publish --org "https://dev.azure.com/company" --feed "test" --name "test" --version "1.0.0" --path /test
Universal Packages is currently in preview.
[Errno 2] No such file or directory: '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool': '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)

...

  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool': '/root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool'
bash-4.4# ls -la /root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool
-rwxr-xr-x    1 root     root        106912 Feb 26 00:50 /root/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.93/artifacttool
```

Windows:
```
 az artifacts universal publish --org "https://dev.azure.com/company" --feed "test" --name "test" --version "1.0.0" --path ./test
Universal Packages is currently in preview.
An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied: 'C:\\Users\\user\\.azure\\azuredevops\\cli\\tools\\artifacttool\\3673036e-14fa-4753-8713-631d5aad8e3c' -> 'C:\\Users\\user\\.azure\\azuredevops\\cli\\tools\\artifacttool\\ArtifactTool_win10-x64_0.2.93'
[WinError 2] The system cannot find the file specified
```

**Comment by zarenner** [comment]
Hi @mbrancato, are you still having issues here? Sorry for the long span of inactivity.

Regarding your original issue: If you can provide more specifics about the exact Ubuntu release, I'd like to try and repro the issue. I'm still guessing there's a change in the SSL libraries in newer Ubuntu and the correct one isn't installed, but I could be wrong.

Regarding the azure-cli docker image: See #217, support was recently added.

Regarding the windows issue: That one is more surprising. Did that repro consistently? I think we might have seen an isolated report of this once before due to Windows Defender scanning, although I'm not sure the symptoms were identical.

**Comment by shreedhargowda** [comment]
I have same issue. I am trying with windows powershell, When I try to publish have the same kind of issue. I use a proxy in a corp network.  I get below error
Universal Packages is currently in preview.
[GetBuildDropManagerAsync] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?

**Comment by zarenner** [comment]
Hi @shreedhargowda - are there any further log lines after that which indicate this is related to a SSL problem?
If not, could you please open this as a new issue?

**Comment by shreedhargowda** [comment]
I keep getting this for a while before command dies,
[GetBuildDropManagerAsync] Try 1/5, retryable exception caught. Retrying in 00:00:01. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 2/5, retryable exception caught. Retrying in 00:00:02.0400000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?
[GetBuildDropManagerAsync] Try 3/5, retryable exception caught. Retrying in 00:00:04.3480000. Details:
Exception.Data didn't contain key LastRequestResponse or its value was null or not a string. Was HttpRequestExceptionExtensions.SetHttpMessagesForTracing called?

**Comment by zarenner** [comment]
Please open a new issue if there's no SSL warning. A fiddler trace (redact any authorization/cookie headers!) would be very useful as well if you're able to collect one, as well as the organization ID if you're willing to share it. I'll loop in the appropriate people.

**Comment by shreedhargowda** [comment]
@zarenner  thanks for quick reply. I will open it as new issue.  can I share the info in a secure way?

**Comment by zarenner** [comment]
Not easily on GitHub unfortunately. On https://developercommunity.visualstudio.com/spaces/21/index.html I believe you can open a (public) issue, and then leave a private comment. Could you please try that and see if that works? If not, I'll find another way.

**Comment by zivillian** [comment]
`export CLR_OPENSSL_VERSION_OVERRIDE=1.1` fixed this for me - see also dotnet/corefx/issues/33179

**Comment by zarenner** [comment]
Closing due to above workaround and lack of activity. @mbrancato (or anyone else with this issue), if you're still having issues please let me know and we can work through this further.
