### ISSUE TITLE
[Bug] PAT fails to login via AzureDevOps Windows build/release agent

### ISSUE THREAD

**Issue by hshui** [Azure/azure-devops-cli-extension#486]
**Describe the bug**
Unable to login via AzureDevOps build/release agent (Hosted VS2017). Piping the PAT or using environment variables to store the PAT to use with "az devops login" command results in invalid PAT and failed authentication.

**To Reproduce**
Azure Cli Version: 
azure-cli (2.0.59)

Azure-Devops extension version: 
azure-devops (0.3.0)

1. In a AzureDevOps release definition define an environment variable AZURE_DEVOPS_EXT_PAT and set it to the PAT with correct permissions.

2. Run a powershell task with the following commands:

```
az extension add --name azure-devops
echo $env:AZURE_DEVOPS_EXT_PAT | az devops login --debug --organization=https://dev.azure.com/myOrg
```

**Expected behavior**
Expected to authenticate as PAT user.

**Screenshots**
![image](https://user-images.githubusercontent.com/10343332/54309357-34336700-458d-11e9-94f8-b8764619035c.png)

**Debug logs**
2019-03-13T19:23:24.0029894Z DEBUG: azext_devops.vstsCompressed.vss_client : Response content: b'{"$id":"1","innerException":null,"message":"TF400813: The user \'\' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}'
2019-03-13T19:23:24.0032861Z DEBUG: msrest.exceptions : TF400813: The user '' is not authorized to access this resource.
2019-03-13T19:23:24.0048439Z DEBUG: TF400813: The user '' is not authorized to access this resource.
2019-03-13T19:23:24.0049169Z Traceback (most recent call last):
2019-03-13T19:23:24.0049751Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\dev\team\credentials.py", line 33, in credential_set
2019-03-13T19:23:24.0050293Z     connection_data = location_client.get_connection_data()
2019-03-13T19:23:24.0050811Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\location\v4_1\location_client.py", line 46, in get_connection_data
2019-03-13T19:23:24.0052164Z     query_parameters=query_parameters)
2019-03-13T19:23:24.0052460Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 72, in _send
2019-03-13T19:23:24.0052882Z     query_parameters=query_parameters)
2019-03-13T19:23:24.0053511Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 111, in _create_request_message
2019-03-13T19:23:24.0053927Z     location = self._get_resource_location(location_id)
2019-03-13T19:23:24.0054077Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 141, in _get_resource_location
2019-03-13T19:23:24.0054276Z     VssClient._locations_cache[self.config.base_url] = self._get_resource_locations(all_host_types=False)
2019-03-13T19:23:24.0054473Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 177, in _get_resource_locations
2019-03-13T19:23:24.0054668Z     response = self._send_request(request, headers=headers)
2019-03-13T19:23:24.0054806Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 64, in _send_request
2019-03-13T19:23:24.0054987Z     self._handle_error(request, response)
2019-03-13T19:23:24.0055149Z   File "C:\Users\VssAdministrator\.azure\cliextensions\azure-devops\azext_devops\vstsCompressed\vss_client.py", line 239, in _handle_error
2019-03-13T19:23:24.0055314Z     raise VstsServiceError(wrapped_exception)
2019-03-13T19:23:24.0055467Z azext_devops.vstsCompressed.exceptions.VstsServiceError: TF400813: The user '' is not authorized to access this resource.
2019-03-13T19:23:24.0055624Z DEBUG: handling generic error
2019-03-13T19:23:24.0160384Z ERROR: Failed to authenticate using the supplied token.

**Additional context**
The evaluation of $env:AZURE_DEVOPS_EXT_PAT  -eq "my_pat_value" was "True". I have also used the PAT on my local machine and validated the PAT works.

I have also tried all the other methods outlined in your login to azure devops guide. [As outlined](https://github.com/Microsoft/azure-devops-cli-extension/blob/master/doc/samples.md#log-in-via-azure-devops-personal-access-token-pat)

**Comment by atbagga** [comment]
@hshui Thank you for reporting the issue. 

When you setup the environment variable AZURE_DEVOPS_EXT_PAT  with the correct PAT token, login command is not required. So in your case if you skip the login command you should be able to directly run the commands and they will try to use the PAT from environment for authentication.
e.g. This script will run without explicit login. 
```
az extension add --name azure-devops
az devops project list --org https://dev.azure.com/myorg
```

I will try to debug the reported issue, but hopefully the above should unblock you. Keep the thread posted if that works.

**Comment by hshui** [comment]
@atbagga Thanks for pointing the login command is not required if the environment variable is used to store the token. That was not obvious from the documentation!

I opted to go with a linux based agent instead since it still supports powershell scripting and maintains the login logic.

**Comment by atbagga** [comment]
Glad that you are unblocked. 

It is strange that same steps work on a linux agent and even with command line script task but not with powershell script on a windows agent. Probably something to do with how the shell is handling the command piping.

**Comment by hshui** [comment]
Actually the script is run with powershell on ubuntu. So for it to not work on Windows is even more confusing.

**Comment by atbagga** [comment]
Filed a relevant bug in the azure pipelines tasks repository. This is the behavior of the powershell task which is causing the issue. 

Test setup: 

myecho.py
```
import sys
token = sys.stdin.readline()
print("Token is " + token)
```

Powershell task script:
```
echo 'test token' | python myecho.py
```

Output on vs2017 agent: 
![image](https://user-images.githubusercontent.com/11888714/58246453-ba7ddd80-7d74-11e9-8c2f-b6e84c6b3fc5.png)

Output on Ubuntu Agent: 
![image](https://user-images.githubusercontent.com/11888714/58246483-ce294400-7d74-11e9-99ae-39c2d242bd83.png)

Closing this issue since there is a workaround for this to get unblocked for using azure devops extension.

**Comment by atbagga** [comment]
Related issue filed in agent repo - https://github.com/microsoft/azure-pipelines-image-generation/issues/975

**Comment by lifesoccult** [comment]
@atbagga this is still an issue. I just ran across it today. Trying workaround. But this should still be addressed and fixed.

**Comment by luisnjuarez** [comment]
@atbagga has this been resolved, I just ran across the same issue. What is the workaround?

**Comment by atbagga** [comment]
> @atbagga has this been resolved, I just ran across the same issue. What is the workaround?

I am no longer maintainer on this project. 

Since this was a more generic issue in Azure Powershell task I think we need to track and follow up there if it got fixed there.
