### ISSUE TITLE
[Bug] Adding user to a group breaks

### ISSUE THREAD

**Issue by kcitdevops** [Azure/azure-devops-cli-extension#664]
Azure Cli Version: 2.0.60
Azure-Devops extension version: 0.10.0

1. Login:
   $PAT | az devops login --org $org
2. Run command:
    az devops security group membership add --group-id [test-project-test]\Contributors --member-id josh.coffin@kingcounty.gov
4. See error:
![image](https://user-images.githubusercontent.com/42781011/59138264-04ec8600-8941-11e9-9441-46c71e16bfc7.png)

az : ERROR: Page not found.  Operation returned an invalid status code of 404.
At line:1 char:1
+ az devops security group membership add --group-id [test-project-test ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Page not...us code of 404.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 377, in _run_job
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 452, in default_command_handler
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\dev\team\security_group.py", line 190, in add_membership
    container_descriptor=group_id)
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\v5_0\graph\graph_client.py", line 102, in add_membership
    route_values=route_values)
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 90, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "C:\Users\coffinj\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 258, in _handle_error
    status_code=response.status_code))
azext_devops.devops_sdk.exceptions.AzureDevOpsClientRequestError: Page not found.  Operation returned an invalid status code of 404.

**Comment by ishitam8** [comment]
Hi,

As you can see from the help text of `az devops security group membership add -h` command, parameter **id** should be a group descriptor and not the group name.
Kindly run the same command with value of id param as group descriptor, and it should work fine for you.
You can find the group descriptor with the help of list project groups command : `az devops security group list`

![GroupMemberAdd](https://user-images.githubusercontent.com/43136080/59190293-f9e06280-8b99-11e9-837b-ae2d8d7d3e35.PNG)


Since, the stack trace is not very helpful here, i would add a custom error message in case of invalid input . Hence, keeping this issue as open till i resolve the stack trace issue.

**Comment by joshlcoffin** [comment]
So- forgive me, to clarify- we need to use the group's ID? How would one get that using the CLI?

**Comment by ishitam8** [comment]
HI @joshlcoffin ,

No, you would need to use group **descriptor**.  Security group commands don't accept GUIDs because they are not unique across different group and user types. You will get the group name to descriptor mapping by running `az devops security group list -p <YOUR-PROJECT-NAME>`

![SecurityGroupList](https://user-images.githubusercontent.com/43136080/59419373-6d77af00-8de8-11e9-8a75-0f323af145c6.PNG)


Let me know if this works for you.

**Comment by geverghe** [comment]
Closing this issue. @joshlcoffin - let me know if the above clarification does not work or if you need any additional help.

**Comment by kcitdevops** [comment]
@ishitam8, @geverghe Ah, sorry, got caught up in several other projects. Yes, this worked! Thank you very much!
