### ISSUE TITLE
Auth documentation could be improved

### ISSUE THREAD

**Issue by LasseNisted** [Azure/azure-devops-cli-extension#670]
Having spend too much time figuring out why our build agent could not download pipeline artifacts via the Azure CLI azure-devops extension, I think the auth documentation could be improved.

I would suggest:

1. Make https://aka.ms/azure-devops-cli-auth point to https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/samples.md#log-in-via-azure-devops-personal-access-token-pat
2. Make it clear that PATs can be set as environment variables based on `$(System.AccessToken)` in a pipeline (the information is currently spread out), like so: https://github.com/Azure/azure-devops-cli-extension/blob/master/doc/samples.md#use-the-azure-devops-extension-with-yaml
3. Improve the `az login --help` to mention the environment variable and that the token will be read from `stdin`.
4. Either mention required rights for `--detect` logic or fail with a meaningful error. It seems the detected information is cached, which in our case meant that the PAT had enough rights for one build agent, but not the other where the information was not cached. This caused some confusion. See also https://developercommunity.visualstudio.com/content/problem/412424/pat-gets-error-when-using-vsts-download-for-a-univ.html and https://developercommunity.visualstudio.com/content/problem/529020/universal-artifact-fails-to-download-without-excep.html which may be related.
5. Additionally, it would be great if the extension could work with the standard auth mechanisms from the az cli to avoid the PAT token altogether.
6. Make the extension part of the default hosted images - with authentication already set up.

**Comment by LasseNisted** [comment]
1. If you run `az devops logout` and `az logout` and then, e.g., `az repos pr list`, you get `Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.`. The link is in the source at: https://github.com/Azure/azure-devops-cli-extension/blob/95fbabf5fb3525088f4d894ee910793895402009/azure-devops/azext_devops/dev/common/services.py#L407 . Great with all the other changes you mention!
2. Definitely! I was not aware of these pages at the time. It is much cleaner than the lengthy samples.md I found.
3. I wrongly mentioned `az login` when i meant `az devops login`. My bad. You thankfully deciphered the meaning and yes, a link from `az devops login` to that page would suffice.
4. The PAT had insufficient permissions. I believe it needs Code->Read permissions to populate `C:\Users\{my user}\.azure\azuredevops\cache\remotes.json` when using `--detect`. Here is a repro:
   1. Create a new organization
   2. Clone the empty default repository.
   3. Run the rest of the commands from inside the clone to enable `--detect`.
   4. Run `az logout` and `az devops logout` to ensure no credentials were left behind.
   5. Run ` az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and got an error `Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.`
   6. Create a new PAT for my user with Build->Read rights.
   7. Run `echo <PAT> | az devops login`
   8. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and get the error
```
The command failed with an unexpected error. Here is the traceback:

The requested resource requires user authentication: https://{myorg}@dev.azure.com/{myorg}/test1/_git/test1/vsts/info
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 560, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 618, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 609, in _run_job
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 588, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 297, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\__init__.py", line 461, in default_command_handler
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\pipelines\runs_artifacts.py", line 25, in run_artifact_download
    organization, project = resolve_instance_and_project(detect=detect, organization=organization, project=project)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 351, in resolve_instance_and_project
    detect=detect, organization=organization, project=project, project_required=project_required)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 321, in resolve_instance_project_and_repo
    git_info = get_vsts_info_from_current_remote_url()
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 383, in get_vsts_info_from_current_remote_url
    info = VstsGitUrlInfo(get_remote_url(VstsGitUrlInfo.is_vsts_url_candidate))
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\vsts_git_url_info.py", line 42, in __init__
    vsts_info = self.get_vsts_info(remote_url)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\vsts_git_url_info.py", line 94, in get_vsts_info
    return GitClient.get_vsts_info_by_remote_url(uri, credentials=credentials)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\v5_0\git\git_client.py", line 33, in get_vsts_info_by_remote_url
    response = git_client._send_request(request, headers)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 254, in _handle_error
    url=request.url))
azext_devops.devops_sdk.exceptions.AzureDevOpsAuthenticationError: The requested resource requires user authentication: https://{myorg}@dev.azure.com/{myorg}/test1/_git/test1/vsts/info
```

4. Repro continued...
   1. Edit the PAT to grant Code->Read rights.
   1. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and get the error `The specified pipeline was not found.`, i.e. it got further and my empty organization does not actually have the artifact I requested.
   1. Edit the PAT to _revoke_ Code->Read rights.
   1. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and _still_ get the error `The specified pipeline was not found.`, so somehow it does not need the Code->Read rights anymore.
   1. Delete `C:\Users\{my user}\.azure\azuredevops\cache\`.
   1.  Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and now get the long stack trace again.
5. Acknowledged.
6. I mean the association to System.AccessToken already in place. Basically something like the first 9 lines of the first script at https://docs.microsoft.com/en-us/azure/devops/cli/azure-devops-cli-in-yaml?view=azure-devops being encapsulated in a pipeline task or being built into the the Azure CLI pipeline task.

**Comment by geverghe** [comment]
1 - Created issue to include the help text with the link to the document in `az devops login` - https://github.com/Azure/azure-devops-cli-extension/issues/686
4 - Raised a bug for this https://github.com/Azure/azure-devops-cli-extension/issues/687 so that we can continue our discussion on the issue thread. Ideally, `--detect` just infers the configuration parameters and as I mentioned does not have anything to do with PAT. However, we can continue our investigation and discussion there. 
6 - The more predominant use case which we see on pipelines is the automation use case where users are not usually using their own credentials but a service account credential to execute actions. Further, the tasks are at a generic CLI task level. For these reasons, there wouldn't be an out of box pipeline CLI task with the authorization recommendation that has been provided. Recommendation would to build/use a pipeline task extension that does this.

I am closing this issue. Feel free to re-open in case you need any additional clarification.
