### ISSUE TITLE
--detect uses Code-Read permission in PAT token to infer configuration

### ISSUE THREAD

**Issue by geverghe** [Azure/azure-devops-cli-extension#687]
**Describe the bug**
Either mention required rights for` --detect logic` or fail with a meaningful error. It seems the detected information is cached, which in our case meant that the PAT had enough rights for one build agent, but not the other where the information was not cached. This caused some confusion. See also https://developercommunity.visualstudio.com/content/problem/412424/pat-gets-error-when-using-vsts-download-for-a-univ.html and https://developercommunity.visualstudio.com/content/problem/529020/universal-artifact-fails-to-download-without-excep.html which may be related.

**Steps to reproduce the behavior:**
The PAT had insufficient permissions. I believe it needs Code->Read permissions to populate `C:\Users\{my user}\.azure\azuredevops\cache\remotes.json` when using `--detect`. Here is a repro:
   1. Create a new organization
   2. Clone the empty default repository.
   3. Run the rest of the commands from inside the clone to enable `--detect`.
   4. Run `az logout` and `az devops logout` to ensure no credentials were left behind.
   5. Run ` az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and got an error `Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.`
   6. Create a new PAT for my user with Build->Read rights.
   7. Run `echo <PAT> | az devops login`
   8. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and get the error
```
The command failed with an unexpected error. Here is the traceback:

The requested resource requires user authentication: https://{myorg}@dev.azure.com/{myorg}/test1/_git/test1/vsts/info
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 560, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 618, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 609, in _run_job
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 588, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\commands\__init__.py", line 297, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-dsvrkf2x\azure-cli-core\azure\cli\core\__init__.py", line 461, in default_command_handler
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\pipelines\runs_artifacts.py", line 25, in run_artifact_download
    organization, project = resolve_instance_and_project(detect=detect, organization=organization, project=project)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 351, in resolve_instance_and_project
    detect=detect, organization=organization, project=project, project_required=project_required)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 321, in resolve_instance_project_and_repo
    git_info = get_vsts_info_from_current_remote_url()
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\services.py", line 383, in get_vsts_info_from_current_remote_url
    info = VstsGitUrlInfo(get_remote_url(VstsGitUrlInfo.is_vsts_url_candidate))
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\vsts_git_url_info.py", line 42, in __init__
    vsts_info = self.get_vsts_info(remote_url)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\dev\common\vsts_git_url_info.py", line 94, in get_vsts_info
    return GitClient.get_vsts_info_by_remote_url(uri, credentials=credentials)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\v5_0\git\git_client.py", line 33, in get_vsts_info_by_remote_url
    response = git_client._send_request(request, headers)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 54, in _send_request
    self._handle_error(request, response)
  File "C:\Users\{my user}\.azure\cliextensions\azure-devops\azext_devops\devops_sdk\client.py", line 254, in _handle_error
    url=request.url))
azext_devops.devops_sdk.exceptions.AzureDevOpsAuthenticationError: The requested resource requires user authentication: https://{myorg}@dev.azure.com/{myorg}/test1/_git/test1/vsts/info
```

4. Repro continued...
   1. Edit the PAT to grant Code->Read rights.
   1. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and get the error `The specified pipeline was not found.`, i.e. it got further and my empty organization does not actually have the artifact I requested.
   1. Edit the PAT to _revoke_ Code->Read rights.
   1. Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and _still_ get the error `The specified pipeline was not found.`, so somehow it does not need the Code->Read rights anymore.
   1. Delete `C:\Users\{my user}\.azure\azuredevops\cache\`.
   1.  Run `az pipelines runs artifact download --run-id 1 --artifact-name a --path .` and now get the long stack trace again.

**Comment by atbagga** [comment]
**Issue:** We have a code path which makes a server call to parse the remote url. This API requires Code-Read permissions. [return GitClient.get_vsts_info_by_remote_url(uri, credentials=credentials)](https://github.com/Azure/azure-devops-cli-extension/blob/3d591e0c6a7548c1d0e65d9e985313cfe05964a3/azure-devops/azext_devops/dev/common/vsts_git_url_info.py#L94)

In short we will get permissions error on trying to create a workitem with a PAT having all work-item permissions if detect is on and command is run from a Azure devops git repository. 

**Workaround:**  Provide organization and project in command params when using a PAT which does not have Code-Read permissions and not depend on detect.

**Fix:** This call should either be all client side parsing OR optional such that on failing the server call with permissions error client should proceed with local git url parsing.

Thanks @LasseNisted for reporting this issue with detailed steps to repro.

**Comment by atbagga** [comment]
@geverghe Since this is a corner scenario and there are cases which might still fail if we try to get it to work without making a server call by depending on local git url parse to detect repo and project information. I would recommend we just handle the error gracefully. 

Instead of throwing a permission error the auto detect will just be skipped and other forms like config will still work. 

This might look inconsistent to some one who runs into this issue where in we should just document it in the git auto detect that it needs code read permissions.
