### ISSUE TITLE
Cannot download universal package from Azure Devops feed

### ISSUE THREAD

**Issue by thedevilfish** [Azure/azure-devops-cli-extension#736]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.11.0.`

**Errors:**
```
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
pip-install-qdpilz60\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 578, in execute
cli\core\commands\__init__.py, ln 636, in _run_jobs_serially
cli\core\commands\__init__.py, ln 627, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-qdpilz60\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 606, in _run_job
...
Azure\CLI2\lib\subprocess.py, ln 709, in __init__
    restore_signals, start_new_session)
Azure\CLI2\lib\subprocess.py, ln 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.69

Extensions:
azure-devops 0.11.0

```

**Comment by thedevilfish** [comment]
Some additional info:

This is part of the log:
```
Universal Packages is currently in preview.
An error occurred while extracting the Universal Packages tooling: [WinError 5] Access is denied:

[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 578, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 636, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 627, in _run_job
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 606, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\commands\__init__.py", line 305, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-qdpilz60\azure-cli-core\azure\cli\core\__init__.py", line 485, in default_command_handler
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\artifacts\universal.py", line 55, in download_package
    return artifact_tool.download_universal(organization, feed, name, version, path, file_filter)
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 39, in download_universal
    return self.run_artifacttool(organization, args, "Downloading")
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\common\artifacttool.py", line 61, in run_artifacttool
    proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 71, in run
    self.start(command_args, env)
  File "C:\Users\mmahmood\.azure\cliextensions\azure-devops\azext_devops\dev\common\external_tool.py", line 39, in start
    env=env)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by magleaso** [comment]
Could you post the full log in its entirety and add the --debug flag please?

**Comment by elbatk** [comment]
Closing this one as we never got full logs - feel free to reopen and reply with logs if you're still seeing this :)
