### ISSUE TITLE
Fails to download artifacts due to cannot find artifacttool

### ISSUE THREAD

**Issue by lizzha** [Azure/azure-devops-cli-extension#764]
## Describe the bug

**Command Name**
`az artifacts universal download
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
[Errno 2] No such file or directory: '/home/azureuser/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.104/artifacttool': '/home/azureuser/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.104/artifacttool'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/azureuser/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.104/artifacttool': '/home/azureuser/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.104/artifacttool'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal download --organization {} --feed {} --name {} --version {} --path {}`

## Environment Summary
```
Linux-4.15.0-1055-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.72

Extensions:
azure-devops 0.12.0

```

**Comment by elbatk** [comment]
It's been a while since we've heard anything here, going to close this one. Would love to hear if any of the above helped, or if you're still having issues. Cheers!

**Comment by JordanCorrea-MS** [comment]
I'm hitting the same issue in an Azure DevOps pipeline that I'm upgrading to use the azure cli to download artifacts.  The issue occurs randomly.  About 2 out of 5 runs fail.  I ran with --debug but the output is very long so here are some interesting snippets...

2022-11-16T20:25:47.9230024Z         az pipelines runs artifact download --artifact-name libftd2xx --path /home/cloudtest/AzureSphereCache/Artifacts/556/libftd2xx --run-id 556 --debug
...
2022-11-16T20:25:47.9294244Z         DEBUG: azext_devops.devops_sdk.client: GET https://msazuresphere@dev.azure.com/msazuresphere/4x4/_git/azsphere-cli/vsts/info
...
2022-11-16T20:25:47.9303175Z         DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Checking for ArtifactTool updates
...
2022-11-16T20:25:47.9303666Z         DEBUG: cli.azext_devops.dev.common.services: PAT is present which can be used against this instance
...
2022-11-16T20:25:48.1093643Z         DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Downloading ArtifactTool from https://0t3vsblobprodcus362.vsblob.vsassets.io/artifacttool/artifacttool-linux-x64-Release_0.2.254.zip?sv=2019-07-07&sr=b&sig=z4QhaYspaJTij0bQnndrabZEUpggpNAi7n0HCqXKz2c%3D&spr=https&se=2022-11-16T21%3A25%3A35Z&sp=r&P1=1668633635&P2=11&P3=2&P4=ac0olmgIITJBw4FGv0kLeK27MVi8XrBPuKMGu0VBCXM%3d
...
2022-11-16T20:25:48.1098164Z         DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Extracting ArtifactTool to /home/cloudtest/.azure/azuredevops/cli/tools/artifacttool/eaa84eac-209d-4c51-90e1-944de7dbb961
...
2022-11-16T20:25:48.1099417Z         DEBUG: cli.azext_devops.dev.common.artifacttool_updater: Moving downloaded ArtifactTool from /home/cloudtest/.azure/azuredevops/cli/tools/artifacttool/322e1528-6472-4281-9199-4cd92101f493 to /home/cloudtest/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.254
...
2022-11-16T20:25:48.1136190Z         DEBUG: cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
2022-11-16T20:25:48.1136654Z         DEBUG: cli.azure.cli.core.util: Traceback (most recent call last):
2022-11-16T20:25:48.1137215Z           File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
2022-11-16T20:25:48.1137602Z             cmd_result = self.invocation.execute(args)
2022-11-16T20:25:48.1138195Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
2022-11-16T20:25:48.1138561Z             raise ex
2022-11-16T20:25:48.1139106Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
2022-11-16T20:25:48.1139570Z             results.append(self._run_job(expanded_arg, cmd_copy))
2022-11-16T20:25:48.1140184Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
2022-11-16T20:25:48.1140596Z             return cmd_copy.exception_handler(ex)
2022-11-16T20:25:48.1141258Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 31, in azure_devops_exception_handler
2022-11-16T20:25:48.1141706Z             reraise(*sys.exc_info())
2022-11-16T20:25:48.1142192Z           File "/opt/az/lib/python3.10/site-packages/six.py", line 703, in reraise
2022-11-16T20:25:48.1142519Z             raise value
2022-11-16T20:25:48.1143060Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
2022-11-16T20:25:48.1143455Z             result = cmd_copy(params)
2022-11-16T20:25:48.1144008Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
2022-11-16T20:25:48.1144421Z             return self.handler(*args, **kwargs)
2022-11-16T20:25:48.1145019Z           File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
2022-11-16T20:25:48.1145491Z             return op(**command_args)
2022-11-16T20:25:48.1146111Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/pipelines/runs_artifacts.py", line 27, in run_artifact_download
2022-11-16T20:25:48.1146585Z             return artifact_tool.download_pipeline_artifact(
2022-11-16T20:25:48.1147229Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 25, in download_pipeline_artifact
2022-11-16T20:25:48.1147726Z             return self.run_artifacttool(organization, args, "Downloading")
2022-11-16T20:25:48.1148377Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/artifacttool.py", line 67, in run_artifacttool
2022-11-16T20:25:48.1148897Z             proc = self._tool_invoker.run(command_args, new_env, initial_progress_message, _process_stderr)
2022-11-16T20:25:48.1149573Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 74, in run
2022-11-16T20:25:48.1150052Z             self.start(command_args, env)
2022-11-16T20:25:48.1150632Z           File "/opt/az/azcliextensions/azure-devops/azext_devops/dev/common/external_tool.py", line 33, in start
2022-11-16T20:25:48.1151026Z             self._proc = subprocess.Popen(
2022-11-16T20:25:48.1151375Z           File "/opt/az/lib/python3.10/subprocess.py", line 969, in __init__
2022-11-16T20:25:48.1151773Z             self._execute_child(args, executable, preexec_fn, close_fds,
2022-11-16T20:25:48.1152167Z           File "/opt/az/lib/python3.10/subprocess.py", line 1845, in _execute_child
2022-11-16T20:25:48.1152576Z             raise child_exception_type(errno_num, err_msg, err_filename)
2022-11-16T20:25:48.1153333Z         FileNotFoundError: [Errno 2] No such file or directory: '/home/cloudtest/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.254/artifacttool'

From the logs it appears that artifacttool is being downloaded successfully but then is missing when it tries to actually execute it.

**Comment by mathiasdevos** [comment]
I also have this problem. I have az CLI configured to automatically download extensions
`az config set extension.use_dynamic_install=yes_without_prompt`

When running "az artifacts universal download ..." I get the same error as mentioned above:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/AzDevOps/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.254/artifacttool'`

I noticed that there is **no** 'artifacttool' in the path
`~/.azure/azuredevops/cli/tools/artifacttool/ArtifactTool_linux-x64_0.2.254`

However, there **is** an artifacttool executable in
`~/.azure/azuredevops/cli/tools/artifacttool/954aecc3-1f91-4b3a-b3b6-e78c5709d9fd`

The command "az extension list" returns the following
`[
  {
    "experimental": false,
    "extensionType": "whl",
    "name": "azure-devops",
    "path": "/home/AzDevOps/.azure/cliextensions/azure-devops",
    "preview": false,
    "version": "0.25.0"
  }
]`

Seems like the artifacttool has been installed in another directory which is not part of the search path of the az CLI
