### ISSUE TITLE
az artifacts publish error

### ISSUE THREAD

**Issue by slawekww** [Azure/azure-devops-cli-extension#834]
## Describe the bug

**Command Name**
`az artifacts universal publish
Extension Name: azure-devops. Version: 0.13.0.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:


'module' object has no attribute 'uuid4'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
AttributeError: 'module' object has no attribute 'uuid4'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az artifacts universal publish --organization {} --feed {} --name {} --version {} --description {} --path {}`

## Environment Summary
```
Linux-4.15.0-58-generic-x86_64-with-centos-7.7.1908-Core
Python 2.7.5
Shell: bash

azure-cli 2.0.74 *

Extensions:
azure-devops 0.13.0

```

**Comment by slawekww** [comment]
Problem was related to network connection to Azure DevOps.
The same script and environment has started work the next day.
