### ISSUE TITLE
[Bug] Getting some errors while executing policies, Please help

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-devops-cli-extension#841]
Issue submitted by @ramakrishnagith here:

https://github.com/Azure/azure-cli-extensions/issues/1007

Can you please check below error
The command failed with an unexpected error. Here is the traceback:
Expecting ',' delimiter: line 13 column 9 (char 251)
Traceback (most recent call last):
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\knack\knack\cli.py", line 206, in invoke
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands_init_.py", line 603, in execute
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands_init_.py", line 661, in _run_jobs_serially
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands_init_.py", line 652, in run_job
File "C:\Users\HP.azure\cliextensions\azure-devops\azext_devops\dev\common\exception_handler.py", line 31, in azure_devops_exception_handler
reraise(*sys.exc_info())
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\six\six.py", line 693, in reraise
File "C:\Users\VSSADM1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands_init.py", line 631, in run_job
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core\commands_init.py", line 306, in call
File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-p8t_6awn\azure-cli-core\azure\cli\core_init_.py", line 485, in default_command_handler
File "C:\Users\HP.azure\cliextensions\azure-devops\azext_devops\dev\repos\policy.py", line 75, in create_policy_configuration_file
configuration = json.load(f)
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json_init_.py", line 299, in load
parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json_init_.py", line 354, in loads
return _default_decoder.decode(s)
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\json\decoder.py", line 355, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 9 (char 251)

**Comment by atbagga** [comment]
@ramakrishnagith this looks like a error in your json file which you are creating. 

**json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 9 (char 251)**

Please verify that your json file is correctly formatted.
