### ISSUE TITLE
[Bug] az artifacts universal download is ignoring path setting

### ISSUE THREAD

**Issue by awegg** [Azure/azure-devops-cli-extension#877]
**Describe the bug**
When I am downloading an universal package the path setting is ignored. The download always goes into the directory where the file got published from. 

**To Reproduce**
Azure Cli Version: 2.0.76
Azure-Devops extension version: 0.14.0

1. login using az login
2. az artifacts universal download --organization "***" --feed "****" --name "file" --version "0.0.1" --path "c:\temp"

**Expected behavior**
Expected that "file" is downloaded to c:\temp\ but in fact it's downloaded to the directory where it was published from (in this case c:\temp\Out).

**Debug logs**
Logs from start of download:
```
Running external command: C:\Users\Alex\.azure\azuredevops\cli\tools\artifacttool\ArtifactTool_win10-x64_0.2.128\artifacttool universal download --service ***service*** --patvar AZURE_DEVOPS_EXT_ARTIFACTTOOL_PATVAR --feed **feed** --package-name ***file*** --package-version 0.0.1 --path c:/temp
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 79d34df3-2210-46a1-96b0-d364f3f962cc
Obtained package metadata
DedupManifestArtifactClient will correlate http requests with X-TFS-Session 79d34df3-2210-46a1-96b0-d364f3f962cc
ArtifactHttpRetryMessageHandler.SendAsync: https://vsblobprodsu6weu.vsblob.visualstudio.com/Afd21f887-6eaf-4f79-a0ab-910259fa2ce6/_apis/dedup/chunks/1D345BCBEAF16C2DDA82A2824B3E36A2298D2202B6E2D54B682E763673054DB901 attempt 1/6 failed with StatusCode RedirectMethod, IsRetryableResponse False
Could not initialize dataport.
Downloaded 0,0 MB out of 8,4 MB (0%).
Downloaded 8,3 MB out of 8,4 MB (98%).
Downloaded 8,4 MB out of 8,4 MB (100%).

Download statistics:
Total Content: 8,4 MB
Physical Content Downloaded: 8,4 MB
Compression Saved: 0,0 MB
Local Caching Saved: 0,0 MB
Chunks Downloaded: 116
Nodes Downloaded: 0

Download completed.
Download complete
Success
Event: CommandInvoker.OnTransformResult [<function _resource_group_transform at 0x042FD1E0>, <function _x509_from_base64_to_hex_transform at 0x042FD228>]
Event: CommandInvoker.OnFilterResult []
{
  "ManifestId": "1D345BCBEAF16C2DDA82A2824B3E36A2298D2202B6E2D54B682E763673054DB901",
  "SuperRootId": "4FF77DAD878E4BFCDD89D66BFD04A3187F51B3D798612DC2257A56FEDB311FC902",
  "Version": "0.0.1"
}

```

**Comment by awegg** [comment]
As soon as I protect the directory where I published the file from, I'm getting an exception from the artifacttool. 
Want to download to c:\temp but excpetion is coming from c:\temp\Out\... Directory. The "Out" Directory was the directory where I published it from. 

Command: `az artifacts universal download --organization "" --feed "*" --name "file" --version "0.0.1" --path "c:\temp"`

End of Log:
`Downloaded 0,0 MB out of 8,4 MB (0%).
handling generic error
cli.azure.cli.core.util : Encountered an unexpected error.
System.UnauthorizedAccessException: Access to the path 'C:\temp\Out\ab52ad3b-de57-4eba-add3-231caaed2735.tmp' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.VisualStudio.Services.Content.Common.FileStreamUtils.OpenFileStreamForAsync(String filePath, FileMode mode, FileAccess fileAccess, FileShare fileShare, FileOptions extraOptions)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.<>c__DisplayClass28_0.<OpenForWrite>b__0()
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.OpenForWrite(String fullPath, FileOptions fileOptions)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadToFileAsync(DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupIdentifier dedupId, String fullPath, UInt64 fileSize, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.<>c__DisplayClass24_0.<<DownloadAsyncWithManifestPath>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.TargetBlockExtensions.SendAllAndCompleteAsync[T1,T2](ITargetBlock`1 targetBlock, IEnumerable`1 inputs, ITargetBlock`1 finalBlock, CancellationToken token)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsyncWithManifestPath(DownloadDedupManifestArtifactOptions downloadOptions, IEnumerable`1 minimatcherFuncs, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadSingleManifestAsync(DownloadDedupManifestArtifactOptions downloadOptions, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsync(DownloadDedupManifestArtifactOptions downloadOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Packaging.UPackClientShared.UPackSharedClient.DownloadAsync(String projectNameOrId, String feedNameOrId, String packageName, String packageVersion, String targetDirectory, IEnumerable`1 minimatchPatterns, CancellationToken cancellationToken)
   at ArtifactTool.Commands.UPackDownloadCommand.<>c__DisplayClass25_0.<<ExecuteAsync>b__0>d.MoveNext() in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommand.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at ArtifactTool.Commands.UPack.UPackExceptionMapper.WithExceptionHandlingAsync(Func`1 act) in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackExceptionMapper.cs:line 39
   at ArtifactTool.Commands.UPackDownloadCommand.ExecuteAsync() in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommand.cs:line 64
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in d:\a\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 100
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 57
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 112
Encountered an unexpected error.
System.UnauthorizedAccessException: Access to the path 'C:\temp\Out\ab52ad3b-de57-4eba-add3-231caaed2735.tmp' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.VisualStudio.Services.Content.Common.FileStreamUtils.OpenFileStreamForAsync(String filePath, FileMode mode, FileAccess fileAccess, FileShare fileShare, FileOptions extraOptions)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.<>c__DisplayClass28_0.<OpenForWrite>b__0()
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.OpenForWrite(String fullPath, FileOptions fileOptions)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClient.DownloadToFileAsync(DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupNode node, String fullPath, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupStoreClientWithDataport.DownloadToFileAsync(IDedupDataPort dataport, DedupIdentifier dedupId, String fullPath, UInt64 fileSize, GetDedupAsyncFunc dedupFetcher, Uri proxyUri, EdgeCache edgeCache, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.<>c__DisplayClass24_0.<<DownloadAsyncWithManifestPath>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.NonSwallowingActionBlock.<>c__DisplayClass5_0`1.<<CreateNonSwallowingFunc>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Content.Common.TargetBlockExtensions.SendAllAndCompleteAsync[T1,T2](ITargetBlock`1 targetBlock, IEnumerable`1 inputs, ITargetBlock`1 finalBlock, CancellationToken token)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsyncWithManifestPath(DownloadDedupManifestArtifactOptions downloadOptions, IEnumerable`1 minimatcherFuncs, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadSingleManifestAsync(DownloadDedupManifestArtifactOptions downloadOptions, Boolean downloadManifestReferences, ISet`1 excludedPaths, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.BlobStore.WebApi.DedupManifestArtifactClient.DownloadAsync(DownloadDedupManifestArtifactOptions downloadOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Packaging.UPackClientShared.UPackSharedClient.DownloadAsync(String projectNameOrId, String feedNameOrId, String packageName, String packageVersion, String targetDirectory, IEnumerable`1 minimatchPatterns, CancellationToken cancellationToken)
   at ArtifactTool.Commands.UPackDownloadCommand.<>c__DisplayClass25_0.<<ExecuteAsync>b__0>d.MoveNext() in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommand.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at ArtifactTool.Commands.UPack.UPackExceptionMapper.WithExceptionHandlingAsync(Func`1 act) in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackExceptionMapper.cs:line 39
   at ArtifactTool.Commands.UPackDownloadCommand.ExecuteAsync() in d:\a\1\s\src\ArtifactTool\Commands\UPack\UPackDownloadCommand.cs:line 64
   at ArtifactTool.Commands.CommandBase.OnExecuteAsync() in d:\a\1\s\src\ArtifactTool\Commands\CommandBase.cs:line 100
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 77
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 62
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 611
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 57
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 145
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](IConsole console, String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 130
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 112`

**Comment by peter-empson-statsnz** [comment]
I suspect I have reproduced this today. In my case I found it was an incorrect assumption in publishing the artifact. I had published a zip file, with --path pointing to the zip. When downloaded, this zip was always put back in the original location, like the reporter experienced. Starting again, first unzipping the archive and uploading with --path pointing to the unzipped folder, download then worked as expected.

It would be nice if the tool could handle zip files.  In my case, I am pushing packages like Apache Tomcat to be pushed to internal servers for automated install. I don't really want to be unzipping these 3rd party zips. Further, the current behavior produces unexpected results, leaving artifacts goodness knows where on the build agent.

**Comment by mjiderhamn** [comment]
The title of this issue should be updated to reflect that this only affects artifacts uploaded as zip files (and not directories).

This is quite annoying if you've built your .zip in a CI environment with some "randomly" named, CI internal directory, and you try to `az artifacts universal download` it. You don't get any error message, even `--debug` doesn't show you where the file was downloaded, it's just secretly put in whatever directory it was in on the build agent.

**Comment by jontreynes** [comment]
fyi @peter-empson-statsnz and @mjiderhamn 

https://github.com/Azure/azure-devops-cli-extension/issues/749#issuecomment-640841144

**Comment by omokoh** [comment]
Closing this issue as has been stale for long.
Please feel free to open is again , in-case required.
