### ISSUE TITLE
az devops login failed

### ISSUE THREAD

**Issue by ironyman** [Azure/azure-devops-cli-extension#894]
This is the command that's failing.
```
az devops login --organization https://msazure.visualstudio.com
ERROR: Failed to unlock the collection!
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/team/credentials.py", line 42, in credential_set
    set_credential(organization=organization, token=token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/_credentials.py", line 33, in set_credential
    cred_store.set_password(key, token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/credential_store.py", line 31, in set_password
    old_token = keyring.get_password(key, self._USERNAME)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 64, in get_password
    collection = self.get_preferred_collection()
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
WARNING:
```
I went to https://msazure.visualstudio.com/_usersSettings/tokens and generated a new token. Still doesn't work.

## Describe the bug

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
Failed to unlock the collection!
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 603, in execute
    raise ex
cli/core/commands/__init__.py, ln 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure-devops/keyring/backends/SecretService.py, ln 64, in get_password
    collection = self.get_preferred_collection()
azure-devops/keyring/backends/SecretService.py, ln 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login --organization {}`

## Environment Summary
```
Linux-5.0.0-31-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.76

Extensions:
azure-devops 0.12.0

```

**Comment by ishitam8** [comment]
Hi @ironyman ,

The fix to avoid storing credentials in keyring in case it has issue is already in master and will be available in next release.
Meanwhile, you can try following solutions.
Do you have an application named "Sea horse" on your system? Or was there a pop-up to enter a password which you might have dismissed by mistake while running this command?

The problem here is, you need to set-up a password to access seahorse which will be inturn used by keyring, and if its already locked, keyring asks you to enter the same password. Without this password, keyring can't store your credentials in Seahorse application.
Thus, setting up of Seahorse is required in this case.

You can check more details in a similar issue on keyring #762
