### ISSUE TITLE
Failure when trying to login

### ISSUE THREAD

**Issue by ironyman** [Azure/azure-devops-cli-extension#945]
## Describe the bug

**Command Name**
`az devops login
Extension Name: azure-devops. Version: 0.12.0.`

**Errors:**
```
Failed to unlock the collection!
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 608, in execute
    raise ex
cli/core/commands/__init__.py, ln 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure-devops/keyring/backends/SecretService.py, ln 64, in get_password
    collection = self.get_preferred_collection()
azure-devops/keyring/backends/SecretService.py, ln 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az devops login --organization {}`

## Environment Summary
```
Linux-5.3.0-28-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.80

Extensions:
azure-devops 0.12.0

```

**Comment by ironyman** [comment]
```
The command failed with an unexpected error. Here is the traceback:

Failed to unlock the collection!
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 608, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 666, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in _run_job
    cmd_copy.exception_handler(ex)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/exception_handler.py", line 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 636, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 493, in default_command_handler
    return op(**command_args)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/team/credentials.py", line 42, in credential_set
    set_credential(organization=organization, token=token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/_credentials.py", line 33, in set_credential
    cred_store.set_password(key, token)
  File "/home/cyl/.azure/cliextensions/azure-devops/azext_devops/dev/common/credential_store.py", line 31, in set_password
    old_token = keyring.get_password(key, self._USERNAME)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 64, in get_password
    collection = self.get_preferred_collection()
  File "/home/cyl/.azure/cliextensions/azure-devops/keyring/backends/SecretService.py", line 58, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

**Comment by ishitam8** [comment]
@ironyman ,

This issue is already fixed. Please update the cli version to latest
`az extension update -n azure-devops`

You can refer #762 and #894 for more details on this.

**Comment by ironyman** [comment]
Ah, thanks
