### ISSUE TITLE
API resource location not registered

### ISSUE THREAD

**Issue by faelin** [Azure/azure-devops-cli-extension#990]
## Describe the bug
Running any command through the azure-devops extension of the azure-cli gives **API resource location not registered error**

### Versioning
```
Mac OS 10.14.6
TFS 2018 (16.131.28601.4)
Python 3.8.1

---

azure-cli                          2.4.0

command-modules-nspkg              2.0.3
core                               2.4.0
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.18.0
```

### Steps to Reproduce:
1. login using az login
2. setup defaults (org, project)
3. az devops login
3. Run command `az repos list`

### Expected Behavior
List of repos in the defined project.

### Attempted Solutions
Remove python-sdk cache (`/Users/me/.azure-devops/python-sdk/cache/`) as suggested in [this comment](https://github.com/Azure/azure-devops-cli-extension/issues/149#issuecomment-383114074) of Issue #149 

## Debug logs
```
❯ az repos list --debug
Command arguments: ['repos', 'list', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10dffce50>, <function OutputProducer.on_global_arguments at 0x10e0d8160>, <function CLIQuery.on_global_arguments at 0x10e117550>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'apim', 'appconfig', 'appservice', 'aro', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'managedservices', 'maps', 'monitor', 'natgateway', 'netappfiles', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.006 seconds.
Loaded module 'acs' in 0.009 seconds.
Loaded module 'advisor' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.008 seconds.
Loaded module 'apim' in 0.018 seconds.
Loaded module 'appconfig' in 0.003 seconds.
Loaded module 'appservice' in 0.010 seconds.
Loaded module 'aro' in 0.006 seconds.
Loaded module 'backup' in 0.005 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.037 seconds.
Loaded module 'batchai' in 0.005 seconds.
Loaded module 'billing' in 0.003 seconds.
Loaded module 'botservice' in 0.006 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.007 seconds.
Loaded module 'cloud' in 0.002 seconds.
Loaded module 'cognitiveservices' in 0.003 seconds.
Loaded module 'configure' in 0.002 seconds.
Loaded module 'consumption' in 0.003 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.011 seconds.
Loaded module 'deploymentmanager' in 0.003 seconds.
Loaded module 'dla' in 0.005 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.003 seconds.
Loaded module 'eventgrid' in 0.003 seconds.
Loaded module 'eventhubs' in 0.004 seconds.
Loaded module 'extension' in 0.002 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.002 seconds.
Loaded module 'hdinsight' in 0.004 seconds.
Loaded module 'interactive' in 0.001 seconds.
Loaded module 'iot' in 0.006 seconds.
Loaded module 'iotcentral' in 0.002 seconds.
Loaded module 'keyvault' in 0.007 seconds.
Loaded module 'kusto' in 0.003 seconds.
Loaded module 'lab' in 0.005 seconds.
Loaded module 'managedservices' in 0.002 seconds.
Loaded module 'maps' in 0.003 seconds.
Loaded module 'monitor' in 0.010 seconds.
Loaded module 'natgateway' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'netappfiles' in 0.004 seconds.
Loaded module 'network' in 0.036 seconds.
Loaded module 'policyinsights' in 0.003 seconds.
Loaded module 'privatedns' in 0.005 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.007 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.003 seconds.
Loaded module 'resource' in 0.012 seconds.
Loaded module 'role' in 0.005 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.003 seconds.
Loaded module 'signalr' in 0.002 seconds.
Loaded module 'sql' in 0.013 seconds.
Loaded module 'sqlvm' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.038 seconds.
Loaded module 'vm' in 0.021 seconds.
Loaded all modules in 0.393 seconds. (note: there's always an overhead with the first module loaded)
Found 1 extensions: ['azure-devops']
Extension compatibility result: is_compatible=True cli_core_version=2.4.0 min_required=2.2.0 max_required=None
Extensions directory: '/Users/me/.azure/cliextensions/azure-devops'
Loaded extension 'azure-devops' in 0.034 seconds.
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x10f0a24c0>]
az_command_data_logger : command args: repos list --debug
metadata file logging enabled - writing logs to '/Users/me/.azure/commands'.
Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x10f0bf9d0>]
Event: CommandInvoker.OnPostArgumentLoad []
Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x10f0f30d0>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x10f0f3280>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x10f767f70>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10e0d81f0>, <function CLIQuery.handle_query_parameter at 0x10e1175e0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x10f0f3160>, <function handler at 0x10f8bfc10>, <function DevCommandsLoader.post_parse_args at 0x1101d2af0>]
az_command_data_logger : extension name: azure-devops
az_command_data_logger : extension version: 0.18.0
GitDetect: Could not detect current remotes based on current working directory.
Command '['git', 'remote', '-v']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/Users/me/.azure/cliextensions/azure-devops/azext_devops/dev/common/git.py", line 106, in get_git_remotes
    output = subprocess.check_output([_GIT_EXE, 'remote', '-v'], stderr=subprocess.STDOUT)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'remote', '-v']' returned non-zero exit status 128.
Detect: Url discovery took 0:00:00.023064
Getting credential: azdevops-cli:https://my_tfs_server/tfs
keyring.backend : Loading KWallet
keyring.backend : Loading SecretService
keyring.backend : Loading Windows
keyring.backend : Loading chainer
keyring.backend : Loading macOS
Keyring backend : keyring.backends.OS_X.Keyring (priority: 5)
Getting credential: azdevops-cli: default
Keyring backend : keyring.backends.OS_X.Keyring (priority: 5)
PAT is present which can be used against this instance
Current cloud config:
AzureCloud
local context is not turned on in / and all its parent directories
trying to get token (temp) for tenant <tenant-guid> and user me@domain.example
attempting to read file /Users/me/.azure/accessTokens.json as utf-8-sig
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - Authority:Performing instance discovery: ...
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - Authority:Performing static instance discovery
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - Authority:Authority validated via static instance discovery
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - CacheDriver:Found 5 potential entries.
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - CacheDriver:Resource specific token found.
adal-python : aacea64d-44b6-409e-a301-256d3afa8e57 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'Pi743S5Pq+u5LWO3KnmD/VPwzqzRY+dOkG8EwW9iS1k=', RefreshTokenId: b'Dk1q0UZ72b/O3+2Tu4ZlBAJXE8RjGUjybBTU+oOaeSw='
instance recieved in validate_token_for_instance https://my_tfs_server/tfs
instance processed in validate_token_for_instance https://my_tfs_server/tfs
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk._file_cache : Loading cache file: /Users/me/.azure-devops/python-sdk/cache/resources.json
azext_devops.devops_sdk._file_cache : attempting to read file /Users/me/.azure-devops/python-sdk/cache/resources.json as utf-8-sig
azext_devops.devops_sdk.connection : File cache miss for resources on: https://my_tfs_server/tfs
azext_devops.devops_sdk._file_cache : Loading cache file: /Users/me/.azure-devops/python-sdk/cache/options.json
azext_devops.devops_sdk._file_cache : attempting to read file /Users/me/.azure-devops/python-sdk/cache/options.json as utf-8-sig
azext_devops.devops_sdk.client : File cache hit for options on: https://my_tfs_server/tfs
azext_devops.devops_sdk.client : Route template: _apis/{resource}/{areaId}
azext_devops.devops_sdk.client : Negotiated api version from '5.0-preview.1' down to '4.1-preview'. This means the client is newer than the server.
azext_devops.devops_sdk.client : GET https://my_tfs_server/tfs/_apis/ResourceAreas
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): my_tfs_server:443
urllib3.connectionpool : https://my_tfs_server:443 "GET /tfs/_apis/ResourceAreas HTTP/1.1" 401 0
msrest.exceptions : The requested resource requires user authentication: https://my_tfs_server/tfs/_apis/ResourceAreas
The requested resource requires user authentication: https://my_tfs_server/tfs/_apis/ResourceAreas
failed while trying to get token for tenant <tenant-guid>
trying to get token (temp) for tenant <tenant-guid> and user me@domain.example
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - Authority:Performing instance discovery: ...
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - Authority:Performing static instance discovery
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - Authority:Authority validzated via static instance discovery
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - TokenRequest:Getting token from cache with refresh if necessary.
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - CacheDriver:finding with query keys: {'_clientId': '...', 'userId': '...'}
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - CacheDriver:Looking for potential cache entries: {'_clientId': '...', 'userId': '...'}
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - CacheDriver:Found 5 potential entries.
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - CacheDriver:Resource specific token found.
adal-python : e9f6911c-9526-47a8-8cd1-48cdbaacc183 - CacheDriver:Returning token from cache lookup, AccessTokenId: b'n4fOR7bDjuimIkUzhQSBxpGSvlt1wShzSCTWqCrs9xs=', RefreshTokenId: b'Dk1q0UZ72b/O3+2Tu4ZlBAJXE8RjGUjybBTU+oOaeSw='
instance recieved in validate_token_for_instance https://my_tfs_server/tfs
instance processed in validate_token_for_instance https://my_tfs_server/tfs
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.connection : File cache miss for resources on: https://my_tfs_server/tfs
azext_devops.devops_sdk.client : Route template: _apis/{resource}/{areaId}
azext_devops.devops_sdk.client : Negotiated api version from '5.0-preview.1' down to '4.1-preview'. This means the client is newer than the server.
azext_devops.devops_sdk.client : GET https://my_tfs_server/tfs/_apis/ResourceAreas
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): my_tfs_server:443
urllib3.connectionpool : https://my_tfs_server:443 "GET /tfs/_apis/ResourceAreas HTTP/1.1" 401 0
msrest.exceptions : The requested resource requires user authentication: https://my_tfs_server/tfs/_apis/ResourceAreas
The requested resource requires user authentication: https://my_tfs_server/tfs/_apis/ResourceAreas
failed while trying to get token for tenant <tenant-guid>
Getting credential: azdevops-cli:https://my_tfs_server/tfs
Keyring backend : keyring.backends.OS_X.Keyring (priority: 5)
Getting credential: azdevops-cli: default
Keyring backend : keyring.backends.OS_X.Keyring (priority: 5)
Creating connection with personal access token.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Azure devops telemetry enabled.
Logging telemetry to azure devops server.
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.client : Route template: _apis/{area}/{resource}
azext_devops.devops_sdk.client : Negotiated api version from '5.0-preview.1' down to '4.1-preview'. This means the client is newer than the server.
azext_devops.devops_sdk.client : POST https://my_tfs_server/tfs/_apis/CustomerIntelligence/Events
azext_devops.devops_sdk.client : Request content: [{'area': 'AzureDevopsCli', 'feature': 'repos', 'properties': {'Command': 'list', 'Args': '', 'ShellType': '/bin/zsh', 'IsInteractive': 'True', 'OutputType': 'json', 'OrgPresentInCommand': False, 'ProjectPresentInCommand': False, 'RepoPresentInCommand': False, 'OrgPickedFromGit': False, 'ProjectPickedFromGit': False, 'RepoPickedFromGit': False, 'OrgPickedFromConfig': True, 'ProjectPickedFromConfig': True}}]
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
azext_devops.devops_sdk.connection : File cache miss for resources on: https://my_tfs_server/tfs
azext_devops.devops_sdk.client : Route template: _apis/{resource}/{areaId}
azext_devops.devops_sdk.client : Negotiated api version from '5.0-preview.1' down to '4.1-preview'. This means the client is newer than the server.
azext_devops.devops_sdk.client : GET https://my_tfs_server/tfs/_apis/ResourceAreas
azext_devops.devops_sdk.client : Request content: None
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
urllib3.connectionpool : Starting new HTTPS connection (1): my_tfs_server:443
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): my_tfs_server:443
urllib3.connectionpool : https://my_tfs_server:443 "POST /tfs/_apis/CustomerIntelligence/Events HTTP/1.1" 204 0
urllib3.connectionpool : https://my_tfs_server:443 "GET /tfs/_apis/ResourceAreas HTTP/1.1" 200 143
azext_devops.devops_sdk.client : Response content: b'{"count":0,"value":null}'
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
handling value error
cli.azure.cli.core.util : API resource location <resource-guid> is not registered on https://my_tfs_server/tfs.
API resource location <resource-guid> is not registered on https://my_tfs_server/tfs.
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2629 in cache
telemetry.check : Negative: The /Users/me/.azure/telemetry.txt was modified at 2020-04-21 12:53:35.075126, which in less than 600.000000 s
command ran in 4.671 seconds.

API resource location <resource-guid> is not registered on https://my_tfs_server/tfs.
```

**Comment by faelin** [comment]
Sigh. My organization URL was missing part of the query path that I thought was unnecessary. It was not. I have resolved my own problem.
